import { IntegrationDirection, IntegrationOutcome, IntegrationProvider } from '@prisma/client';

/**
 * What a caller hands the recorder. Everything except provider/operation/direction/
 * outcome is optional: a quote has no order yet, a worker has no requestId.
 */
export interface IntegrationLogEntry {
  provider: IntegrationProvider;
  /** The provider's OWN word for the call (RATE, GENERATE_CNOTE, charge, WEBHOOK…). */
  operation: string;
  direction: IntegrationDirection;
  /** Shared by every attempt and the application-outcome record of one logical call. */
  operationId: string;
  attempt?: number | null;
  maxAttempts?: number | null;
  requestId?: string | null;
  correlationId?: string | null;
  orderId?: string | null;
  paymentId?: string | null;
  shipmentId?: string | null;
  method?: string | null;
  endpoint?: string | null;
  httpStatus?: number | null;
  durationMs?: number | null;
  applicationOutcome: IntegrationOutcome;
  errorClass?: string | null;
  errorMessage?: string | null;
  /** RAW body text; the recorder sanitizes it (never store an already-logged string). */
  requestBody?: string | null;
  requestContentType?: string | null;
  /** RAW response text; sanitized by the recorder. */
  responseBody?: string | null;
  responseContentType?: string | null;
  /** Already-parsed payloads (webhook DTOs); sanitized structurally. */
  requestPayload?: unknown;
  responsePayload?: unknown;
}

/**
 * The narrow surface the HTTP transports depend on. Keeping it an interface (not the
 * Nest service) means `executeShippingRequest` / `executeMidtransRequest` stay pure
 * functions that a unit test can call with a 3-line fake.
 */
export interface IntegrationRecorder {
  /** Fire-and-forget. MUST NOT throw and MUST NOT be awaited by business code. */
  record(entry: IntegrationLogEntry): void;
}

/** Business context a provider supplies; the transport owns everything else. */
export interface IntegrationCallContext {
  provider: IntegrationProvider;
  operation: string;
  recorder?: IntegrationRecorder;
  /**
   * Pre-generated by a caller that must append its OWN application-outcome record
   * for the same logical call (JNE cnote parsing, Midtrans body rejection). When
   * absent the transport generates one.
   */
  operationId?: string;
  orderId?: string | null;
  paymentId?: string | null;
  shipmentId?: string | null;
  correlationId?: string | null;
}
